// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('web', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('web', async function() {
    await driver.get("https://zeus.tjpa.jus.br/")
    await driver.manage().window().setRect({ width: 616, height: 813 })
    await driver.findElement(By.css(".st-emotion-cache-f03grt")).click()
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("danilo.nicioka")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Ad@maz080212")
    await driver.findElement(By.id("kc-login")).click()
    await driver.findElement(By.css(".st-emotion-cache-b0y9n5")).click()
    await driver.findElement(By.css("input")).sendKeys("/tmp/zeus/video/zeusteste.mp4")
    await driver.wait(until.elementLocated(By.css(".stElementContainer:nth-child(9) p")), 300000)
    let element = driver.findElement(By.css('stElementContainer:nth-child(9) p'));
    await driver.actions().scroll(0, 0, 0, 0, element).perform();
  })
})
